default_environment: dev
project_id: 019a5edb-9ad2-7f99-9971-bcd2c413e4ec

environments:
- name: dev
  env:
    RAW_WEATHER_CSV: ./raw/weather_daily.csv
    RAW_FORECAST_CSV: ./raw/weather_forecast_daily.csv
- name: staging
- name: prod

plugins:
  extractors:
    # 1) Meteostat : historique journalier (inchangé)
  - name: tap-rest-api-msdk
    namespace: tap_rest_api_msdk
    variant: widen
    pip_url: tap-rest-api-msdk==1.4.2
    config:
      auth_type: none
      api_url: https://meteostat.p.rapidapi.com
      rate_limit:
        max_per_second: '4'
      streams:
      - name: weather_daily
        path: /point/daily
        headers:
          x-rapidapi-key: ${METEOSTAT_KEY}
          x-rapidapi-host: meteostat.p.rapidapi.com
        params:
          lat: ${LAT}
          lon: ${LON}
          start: ${START}
          end: ${END}
          tz: ${TZ}
        records_path: $.data[*]
        schema:
          primary_key: [date, lat, lon]
          properties:
            date: {type: [string]}
            tavg: {type: [number, 'null']}
            tmin: {type: [number, 'null']}
            tmax: {type: [number, 'null']}
            prcp: {type: [number, 'null']}
            snow: {type: [number, 'null']}
            wdir: {type: [number, 'null']}
            wspd: {type: [number, 'null']}
            wpgt: {type: [number, 'null']}
            pres: {type: [number, 'null']}
            tsun: {type: [number, 'null']}
            lat: {type: [string, number, 'null']}
            lon: {type: [string, number, 'null']}

    # 2) WeatherAPI : prévisions journalières (NOUVEL extracteur)
  - name: tap-weatherapi-forecast
    namespace: tap_rest_api_msdk
    variant: widen
    pip_url: tap-rest-api-msdk==1.4.2
    executable: tap-rest-api-msdk
    config:
      auth_type: none
      api_url: https://weatherapi-com.p.rapidapi.com
      rate_limit:
        max_per_second: '4'
      streams:
      - name: weather_forecast_daily
        path: /forecast.json
        headers:
          X-RapidAPI-Key: ${WEATHERAPI_KEY}           # à mettre dans ton .env
          X-RapidAPI-Host: weatherapi-com.p.rapidapi.com
        params:
          q: ${LOCATION}          # ex: "34.0209,-6.8416"
          days: ${FORECAST_DAYS}       # nb de jours de prévision (3 par défaut)
          aqi: no
          alerts: no
            # Chaque élément = un jour dans forecastday
        records_path: $.forecast.forecastday[*]
        schema:
          primary_key: [date]
          properties:
            date: {type: [string]}
            date_epoch: {type: [integer, 'null']}
            day_maxtemp_c: {type: [number, 'null']}
            day_mintemp_c: {type: [number, 'null']}
            day_avgtemp_c: {type: [number, 'null']}
            day_totalprecip_mm: {type: [number, 'null']}
            day_avghumidity: {type: [number, 'null']}
            day_condition_text: {type: [string, 'null']}
            day_uv: {type: [number, 'null']}

  loaders:
  - name: target-csv
    variant: meltanolabs
    pip_url: meltanolabs-target-csv
    config:
      destination_path: ./raw
      add_timestamp_prefix: 'false'
      delimiter: ','

  utilities:
  - name: dbt-duckdb
    variant: jwills
    pip_url: dbt-core dbt-duckdb meltano-dbt-ext~=0.3.0
    settings:
    - name: project_dir
      value: transform

        # très important : on enlève completement 'profiles_dir'
        # pour ne plus forcer --profiles-dir en CLI

    - name: skip_pre_invoke
      value: true



    # utilitaire Python pour nettoyer le CSV historique
    env:
      MELTANO_DBT_EXT_SKIP_PRE_INVOKE: 'true'

    config:
      skip_pre_invoke: 'true'
      target_path: transform/target
  - name: weather-tools
    namespace: weather_tools
    pip_url: pandas
    executable: python
    commands:
      clean-csv: scripts/clean_csv.py ./raw/weather_daily.csv
      clean-forecast-csv: scripts/clean_forecast_csv.py ./raw/weather_forecast_daily.csv
settings:
- name: RAW_WEATHER_CSV
  value: ./raw/weather_daily.csv
- name: RAW_FORECAST_CSV
  value: ./raw/weather_forecast_daily.csv

jobs:
- name: extract_clean_build
  tasks:
      # 1) Historique Meteostat → CSV
  - tap-rest-api-msdk target-csv
      # 2) Forecast WeatherAPI → autre CSV (raw/weather_forecast_daily.csv)
  - tap-weatherapi-forecast target-csv
      # 3) Nettoyage de weather_daily.csv
  - weather-tools:clean-csv
  - weather-tools:clean-forecast-csv
      # 4) dbt sur DuckDB
  - dbt-duckdb:run
